// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDFzl0s-Q2jTWqifBLncO5EQ_ev17EMQU',
    appId: '1:916469070264:web:8c1766ed81a154d6e0774d',
    messagingSenderId: '916469070264',
    projectId: 'pharmago-1a614',
    authDomain: 'pharmago-1a614.firebaseapp.com',
    storageBucket: 'pharmago-1a614.firebasestorage.app',
    measurementId: 'G-9FS6RFBVPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3YWxwrdDhNAFEfT4U8g5dB47lCBXYdnI',
    appId: '1:916469070264:android:bccc98f4390a2493e0774d',
    messagingSenderId: '916469070264',
    projectId: 'pharmago-1a614',
    storageBucket: 'pharmago-1a614.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJML6YA_JPTh9IsDwm5FxGdoD4es6Ozg',
    appId: '1:916469070264:ios:82666104f3947a61e0774d',
    messagingSenderId: '916469070264',
    projectId: 'pharmago-1a614',
    storageBucket: 'pharmago-1a614.firebasestorage.app',
    iosBundleId: 'com.example.pharmago',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJML6YA_JPTh9IsDwm5FxGdoD4es6Ozg',
    appId: '1:916469070264:ios:82666104f3947a61e0774d',
    messagingSenderId: '916469070264',
    projectId: 'pharmago-1a614',
    storageBucket: 'pharmago-1a614.firebasestorage.app',
    iosBundleId: 'com.example.pharmago',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDFzl0s-Q2jTWqifBLncO5EQ_ev17EMQU',
    appId: '1:916469070264:web:be4afd703dbfbc58e0774d',
    messagingSenderId: '916469070264',
    projectId: 'pharmago-1a614',
    authDomain: 'pharmago-1a614.firebaseapp.com',
    storageBucket: 'pharmago-1a614.firebasestorage.app',
    measurementId: 'G-T20DYSJWB9',
  );
}
